### ISSUE TITLE
GET build number error with the new lambdacd-git

### ISSUE THREAD

**Issue by arichiardi** [sroidl/lambda-ui#99]
Hello! It looks like I consistently get the following error if I use this ui with `lambdacd-git 0.2.0`. Just wanted to report a possible breakage, and I don't even know where it belongs:

```
Tue May 30 10:14:53 PDT 2017 [worker-1] ERROR - GET /ep/lambdaui/api/builds
java.lang.IllegalArgumentException: No implementation of method: :get-all of protocol: #'lambdacd.internal.pipeline-state/PipelineStateComponent found for class: nil
	at clojure.core$_cache_protocol_fn.invokeStatic(core_deftype.clj:568)
	at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:560)
	at lambdacd.internal.pipeline_state$eval9598$fn__9638$G__9585__9643.invoke(pipeline_state.clj:4)
	at lambdaui.common.common$state_from_pipeline.invokeStatic(common.clj:7)
	at lambdaui.common.common$state_from_pipeline.invoke(common.clj:6)
	at lambdaui.api_legacy$subscribe_to_summary_update.invokeStatic(api_legacy.clj:79)
	at lambdaui.api_legacy$subscribe_to_summary_update.invoke(api_legacy.clj:71)
	at lambdaui.api_legacy$api_routes$fn__14485.invoke(api_legacy.clj:116)
	at compojure.core$wrap_response$fn__2554.invoke(core.clj:158)
	at compojure.core$wrap_route_middleware$fn__2538.invoke(core.clj:128)
	at compojure.core$wrap_route_info$fn__2543.invoke(core.clj:137)
	at compojure.core$wrap_route_matches$fn__2547.invoke(core.clj:146)
	at compojure.core$routing$fn__2562.invoke(core.clj:185)
	at clojure.core$some.invokeStatic(core.clj:2592)
	at clojure.core$some.invoke(core.clj:2583)
	at compojure.core$routing.invokeStatic(core.clj:185)
	at compojure.core$routing.doInvoke(core.clj:182)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$apply.invoke(core.clj:641)
	at compojure.core$routes$fn__2566.invoke(core.clj:192)
	at compojure.core$routing$fn__2562.invoke(core.clj:185)
	at clojure.core$some.invokeStatic(core.clj:2592)
	at clojure.core$some.invoke(core.clj:2583)
	at compojure.core$routing.invokeStatic(core.clj:185)
	at compojure.core$routing.doInvoke(core.clj:182)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$apply.invoke(core.clj:641)
	at compojure.core$routes$fn__2566.invoke(core.clj:192)
	at compojure.core$make_context$handler__2632.invoke(core.clj:285)
	at compojure.core$make_context$fn__2634.invoke(core.clj:293)
	at compojure.core$routing$fn__2562.invoke(core.clj:185)
	at clojure.core$some.invokeStatic(core.clj:2592)
	at clojure.core$some.invoke(core.clj:2583)
	at compojure.core$routing.invokeStatic(core.clj:185)
	at compojure.core$routing.doInvoke(core.clj:182)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$apply.invoke(core.clj:641)
	at compojure.core$routes$fn__2566.invoke(core.clj:192)
	at ring.middleware.params$wrap_params$fn__13520.invoke(params.clj:67)
	at ring.middleware.json$wrap_json_response$fn__14532.invoke(json.clj:65)
	at compojure.core$routing$fn__2562.invoke(core.clj:185)
	at clojure.core$some.invokeStatic(core.clj:2592)
	at clojure.core$some.invoke(core.clj:2583)
	at compojure.core$routing.invokeStatic(core.clj:185)
	at compojure.core$routing.doInvoke(core.clj:182)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$apply.invoke(core.clj:641)
	at compojure.core$routes$fn__2566.invoke(core.clj:192)
	at compojure.core$make_context$handler__2632.invoke(core.clj:285)
	at compojure.core$make_context$fn__2634.invoke(core.clj:293)
	at compojure.core$routing$fn__2562.invoke(core.clj:185)
	at clojure.core$some.invokeStatic(core.clj:2592)
	at clojure.core$some.invoke(core.clj:2583)
	at compojure.core$routing.invokeStatic(core.clj:185)
	at compojure.core$routing.doInvoke(core.clj:182)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$apply.invoke(core.clj:641)
	at compojure.core$routes$fn__2566.invoke(core.clj:192)
	at org.httpkit.server.HttpHandler.run(RingHandler.java:91)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```

Thanks for this you, it looks awesomely nice!

**Comment by flosell** [comment]
Hmm, just on first glance: The error says `found for class: nil`. Can you double-check you are passing the the result of `assemble-pipeline` to `pipeline-routes`/`ui-for`?

**Comment by arichiardi** [comment]
Probably the issue was exactly that one, I have bumped to `0.13.2` and retried just switching to `lambdaui` namespace and it works correctly now again. Closing, sorry for the noise.

**Comment by arichiardi** [comment]
I am going to write here another question though: when you say that the features are not there yet, which features are at the moment missing?
